#!/bin/sh
#

# Package
PACKAGE="nomad"
DNAME="nomad"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
DIR_NOMAD="${INSTALL_DIR}/nomad"
CONF_DIR="${DIR_NAME}/conf.d"
ALT_CONF_DIR="/etc/nomad"
NOMAD="${DIR_NOMAD}/nomad"
PID_FILE="/var/run/nomad.pid"
LOG_FILE="/var/log/nomad.log"

# If configurations are found in $ALT_CONF_DIR, use it
if [ -d "${ALT_CONF_DIR}" ];
then
    CONF_DIR="${ALT_CONF_DIR}"
fi
ARGS="agent -config=${CONF_DIR}"

export HOME=${DIR_NOMAD}
export USER=root
export USERNAME=root


start_daemon ()
{
    echo "Using configuration file in ${CONFIG_DIR}" >> $LOG_FILE
    ${NOMAD} $ARGS >> ${LOG_FILE} 2>&1 &
    echo $! > ${PID_FILE}
}

stop_daemon ()
{
    kill `cat ${PID_FILE}`
    wait_for_status 1 20 || kill -9 `cat ${PID_FILE}`
    rm -f ${PID_FILE}
}

daemon_status ()
{
    if [ -f ${PID_FILE} ] && kill -0 `cat ${PID_FILE}` > /dev/null 2>&1; then
        return
    fi
    rm -f ${PID_FILE}
    return 1
}

wait_for_status ()
{
    counter=$2
    while [ ${counter} -gt 0 ]; do
        daemon_status
        [ $? -eq $1 ] && return
        let counter=counter-1
        sleep 1
    done
    return 1
}


case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
        else
            echo Starting ${DNAME} ...
            start_daemon
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
        else
            echo ${DNAME} is not running
        fi
        ;;
    restart)
        stop_daemon
        start_daemon
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    log)
        echo ${LOG_FILE}
        ;;
    *)
        exit 1
        ;;
esac
